apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tyk-schemas
  annotations:
    github.com/project-slug: Letzltd/tyk-schemas
spec:
  type: other
  lifecycle: unknown
  owner: guests
